In [7]:
import pandas as pd

df = pd.read_csv("Titanic-Dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [8]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [4]:
df.describe()

,UNDER_CONSTRUCTION,RERA,BHK_NO.,SQUARE_FT,READY_TO_MOVE,RESALE,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
count,29451.000000,29451.000000,29451.000000,2.945100e+04,29451.000000,29451.000000,29451.000000,29451.000000,29451.000000
mean,0.179756,0.317918,2.392279,1.980217e+04,0.820244,0.929578,21.300255,76.837695,142.898746
std,0.383991,0.465675,0.879091,1.901335e+06,0.383991,0.255861,6.205306,10.557747,656.880713
min,0.000000,0.000000,1.000000,3.000000e+00,0.000000,0.000000,-37.713008,-121.761248,0.250000
25%,0.000000,0.000000,2.000000,9.000211e+02,1.000000,1.000000,18.452663,73.798100,38.000000
50%,0.000000,0.000000,2.000000,1.175057e+03,1.000000,1.000000,20.750000,77.324137,62.000000
75%,0.000000,1.000000,3.000000,1.550688e+03,1.000000,1.000000,26.900926,77.828740,100.000000
max,1.000000,1.000000,20.000000,2.545455e+08,1.000000,1.000000,59.912884,152.962676,30000.000000

In [10]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [12]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [13]:
df.drop("Cabin", axis=1, inplace=True)

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Sex"] = le.fit_transform(df["Sex"])

In [15]:
df = pd.get_dummies(df, columns=["Embarked"])

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
import matplotlib.pyplot as plt

plt.hist(df["Age"], bins=20)

plt.xlabel("Age")
plt.ylabel("Passengers")
plt.title("Age Distribution")

plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [18]:
%pip install matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeable
Collecting matplotlib
  Downloading matplotlib-3.11.0-cp313-cp313-win_amd64.whl.metadata (80 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.63.0-cp313-cp313-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in C:\Users\PAWAN TIWARI\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: packaging>=20.0 in C:\Users\PAWAN TIWARI\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in C:\Users\PAWAN TIWARI\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (12.2.0)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\PAWAN TIWARI\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in C:\Users\PAWAN TIWARI\AppData\Roaming\Python\Python313\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: tzdata in C:\Users\PAWAN TIWARI\AppData\Roaming\Python\Python313\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\PAWAN TIWARI\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.11.0-cp313-cp313-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------- ----------------------------- 2.4/9.3 MB 10.9 MB/s eta 0:00:01
   ----------------- ---------------------- 4.2/9.3 MB 9.9 MB/s eta 0:00:01
   ------------------------------ --------- 7.1/9.3 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 11.4 MB/s  0:00:00
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp313-cp313-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 13.9 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp313-cp313-win_amd64.whl (73 kB)
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn

   ---------------------------------------- 0/7 [pyparsing]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ---------------------- ----------------- 4/7 [contourpy]
   ---------------------- ----------------- 4/7 [contourpy]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------------- 7/7 [seaborn]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.63.0 kiwisolver-1.5.0 matplotlib-3.11.0 pyparsing-3.3.2 seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\PAWAN TIWARI\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.